//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Archive()
        {
            this.Document = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public int Shelf { get; set; }
        public int Ledge { get; set; }
        public int Sector { get; set; }
        public string SectorSerialNumber { get; set; }
        public bool IsFilled { get; set; }
        public int PiecesInSector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Document { get; set; }
    }
}
