//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOfferrings
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime DateGiven { get; set; }
        public System.DateTime DateReturn { get; set; }
        public bool IsOverdue { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Document Document { get; set; }
    }
}
