//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.ClientOfferrings = new HashSet<ClientOfferrings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Theme { get; set; }
        public string SerialNumber { get; set; }
        public int Place { get; set; }
        public int AvalablePieces { get; set; }
        public System.DateTime DateRegistered { get; set; }
    
        public virtual Archive Archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOfferrings> ClientOfferrings { get; set; }
        public virtual DocumentTheme DocumentTheme { get; set; }
    }
}
