//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchiveEntities : DbContext
    {
        public ArchiveEntities()
            : base("name=ArchiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archive> Archive { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientOfferrings> ClientOfferrings { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentTheme> DocumentTheme { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
